/* domain/library.js
   The complete list of 55 titles the C engine knows about.
   Kept here (domain layer) so the HTTP API can serve it without touching the C engine. */

const TITLES = [
  // Movies
  { type:'Movie', title:'Interstellar',                        year:2014, genre:'scifi',   mood:'deep',     timeNeed:'medium', social:'any',   rating:8.7, desc:'Explorers travel through a wormhole to save humanity.' },
  { type:'Movie', title:'Mad Max: Fury Road',                  year:2015, genre:'action',  mood:'intense',  timeNeed:'short',  social:'group', rating:8.1, desc:'A relentless chase across a post-apocalyptic desert.' },
  { type:'Movie', title:'Parasite',                            year:2019, genre:'drama',   mood:'intense',  timeNeed:'medium', social:'any',   rating:8.5, desc:'A poor family schemes into a wealthy household.' },
  { type:'Movie', title:'The Grand Budapest Hotel',            year:2014, genre:'comedy',  mood:'light',    timeNeed:'short',  social:'any',   rating:8.1, desc:'A concierge and his protege chase a stolen painting.' },
  { type:'Movie', title:'Hereditary',                          year:2018, genre:'horror',  mood:'intense',  timeNeed:'medium', social:'group', rating:7.3, desc:'A family unravels terrifying secrets after a death.' },
  { type:'Movie', title:'My Neighbor Totoro',                  year:1988, genre:'cozy',    mood:'relaxed',  timeNeed:'short',  social:'any',   rating:8.1, desc:'Two girls befriend a forest spirit in rural Japan.' },
  { type:'Movie', title:'Blade Runner 2049',                   year:2017, genre:'scifi',   mood:'deep',     timeNeed:'medium', social:'solo',  rating:8.0, desc:'A blade runner uncovers a society-ending secret.' },
  { type:'Movie', title:'John Wick',                           year:2014, genre:'action',  mood:'intense',  timeNeed:'short',  social:'group', rating:7.4, desc:'A retired hitman seeks vengeance for his dog.' },
  { type:'Movie', title:'Whiplash',                            year:2014, genre:'drama',   mood:'intense',  timeNeed:'short',  social:'solo',  rating:8.5, desc:'A young drummer is pushed to the brink by his teacher.' },
  { type:'Movie', title:'Superbad',                            year:2007, genre:'comedy',  mood:'light',    timeNeed:'short',  social:'group', rating:7.6, desc:'Two friends chase one last wild night before graduation.' },
  { type:'Movie', title:'Get Out',                             year:2017, genre:'horror',  mood:'intense',  timeNeed:'short',  social:'group', rating:7.8, desc:'A visit to a girlfriend\'s family turns sinister.' },
  { type:'Movie', title:'Amelie',                              year:2001, genre:'cozy',    mood:'relaxed',  timeNeed:'medium', social:'any',   rating:8.3, desc:'A shy Parisian secretly orchestrates joy for others.' },
  { type:'Movie', title:'Dune',                                year:2021, genre:'scifi',   mood:'intense',  timeNeed:'medium', social:'any',   rating:8.0, desc:'A noble heir confronts destiny on a deadly desert planet.' },
  { type:'Movie', title:'The Dark Knight',                     year:2008, genre:'action',  mood:'intense',  timeNeed:'medium', social:'group', rating:9.0, desc:'Batman faces chaos incarnate in the Joker.' },
  { type:'Movie', title:'The Shawshank Redemption',            year:1994, genre:'drama',   mood:'deep',     timeNeed:'medium', social:'any',   rating:9.3, desc:'Two prisoners bond over decades, finding hope.' },
  { type:'Movie', title:'Into the Spider-Verse',               year:2018, genre:'action',  mood:'light',    timeNeed:'medium', social:'group', rating:8.4, desc:'A teen becomes Spider-Man across a multiverse.' },
  { type:'Movie', title:'The Thing',                           year:1982, genre:'horror',  mood:'intense',  timeNeed:'medium', social:'group', rating:8.2, desc:'Antarctic researchers face a shape-shifting alien.' },
  { type:'Movie', title:'Spirited Away',                       year:2001, genre:'cozy',    mood:'relaxed',  timeNeed:'medium', social:'any',   rating:8.6, desc:'A girl wanders a spirit world to save her parents.' },
  { type:'Movie', title:'Everything Everywhere All at Once',   year:2022, genre:'drama',   mood:'deep',     timeNeed:'medium', social:'any',   rating:7.8, desc:'A laundromat owner saves the multiverse and her family.' },
  { type:'Movie', title:'Mission: Impossible - Fallout',       year:2018, genre:'action',  mood:'intense',  timeNeed:'medium', social:'group', rating:7.7, desc:'Ethan Hunt races to stop a nuclear catastrophe.' },
  { type:'Movie', title:'Past Lives',                          year:2023, genre:'drama',   mood:'deep',     timeNeed:'short',  social:'solo',  rating:7.8, desc:'Two childhood friends reunite across decades.' },
  { type:'Movie', title:'Hot Fuzz',                            year:2007, genre:'comedy',  mood:'light',    timeNeed:'medium', social:'group', rating:7.8, desc:'A top cop is sent to a deceptively sleepy village.' },
  { type:'Movie', title:'Alien',                               year:1979, genre:'horror',  mood:'intense',  timeNeed:'medium', social:'any',   rating:8.5, desc:'A space crew is hunted by a perfect organism.' },
  { type:'Movie', title:'Chef',                                year:2014, genre:'cozy',    mood:'relaxed',  timeNeed:'short',  social:'any',   rating:7.3, desc:'A chef rediscovers his passion on a food-truck trip.' },
  { type:'Movie', title:'Arrival',                             year:2016, genre:'scifi',   mood:'deep',     timeNeed:'short',  social:'solo',  rating:7.9, desc:'A linguist deciphers an alien language to prevent war.' },
  { type:'Movie', title:'Top Gun: Maverick',                   year:2022, genre:'action',  mood:'intense',  timeNeed:'medium', social:'group', rating:8.2, desc:'A legendary pilot trains a new generation.' },
  { type:'Movie', title:'La La Land',                          year:2016, genre:'drama',   mood:'light',    timeNeed:'medium', social:'any',   rating:8.0, desc:'A pianist and an actress chase dreams and each other.' },
  { type:'Movie', title:'The Witch',                           year:2015, genre:'horror',  mood:'intense',  timeNeed:'short',  social:'solo',  rating:6.9, desc:'A Puritan family is torn apart by evil in the woods.' },
  { type:'Movie', title:'Knives Out',                          year:2019, genre:'comedy',  mood:'intense',  timeNeed:'medium', social:'group', rating:7.9, desc:'A detective untangles a family\'s murder mystery.' },
  { type:'Movie', title:'Coco',                                year:2017, genre:'cozy',    mood:'deep',     timeNeed:'short',  social:'group', rating:8.4, desc:'A boy journeys to the Land of the Dead for his family.' },

  // Games
  { type:'Game', title:'Zelda: Breath of the Wild',    year:2017, genre:'action',  mood:'relaxed', timeNeed:'long',   social:'solo',  rating:9.7, desc:'Explore a vast open world of ruins, shrines, and freedom.' },
  { type:'Game', title:'Elden Ring',                   year:2022, genre:'action',  mood:'intense', timeNeed:'long',   social:'solo',  rating:9.5, desc:'Conquer a brutal, mysterious open world.' },
  { type:'Game', title:'Stardew Valley',               year:2016, genre:'cozy',    mood:'relaxed', timeNeed:'long',   social:'group', rating:8.9, desc:'Inherit a farm and build a quiet life in the valley.' },
  { type:'Game', title:'DOOM Eternal',                 year:2020, genre:'action',  mood:'intense', timeNeed:'short',  social:'solo',  rating:8.4, desc:'Rip and tear through demons at blistering speed.' },
  { type:'Game', title:'Portal 2',                     year:2011, genre:'scifi',   mood:'light',   timeNeed:'medium', social:'group', rating:9.5, desc:'Solve mind-bending portal puzzles with razor wit.' },
  { type:'Game', title:'Red Dead Redemption 2',        year:2018, genre:'drama',   mood:'deep',    timeNeed:'long',   social:'solo',  rating:9.7, desc:'Live the twilight of the outlaw era.' },
  { type:'Game', title:'Resident Evil 2 Remake',       year:2019, genre:'horror',  mood:'intense', timeNeed:'medium', social:'solo',  rating:8.6, desc:'Survive a zombie-infested city as a rookie cop.' },
  { type:'Game', title:'Super Mario Odyssey',          year:2017, genre:'action',  mood:'light',   timeNeed:'medium', social:'group', rating:9.4, desc:'Hop across vibrant kingdoms to rescue the Princess.' },
  { type:'Game', title:'Hades',                        year:2020, genre:'action',  mood:'intense', timeNeed:'medium', social:'solo',  rating:9.3, desc:'Battle out of the Underworld in a slick rogue-like.' },
  { type:'Game', title:'Disco Elysium',                year:2019, genre:'drama',   mood:'deep',    timeNeed:'long',   social:'solo',  rating:9.1, desc:'A broken detective solves a murder and his own mind.' },
  { type:'Game', title:'It Takes Two',                 year:2021, genre:'action',  mood:'light',   timeNeed:'medium', social:'group', rating:8.8, desc:'A split couple cooperates through a toy-box world.' },
  { type:'Game', title:'Hollow Knight',                year:2017, genre:'action',  mood:'deep',    timeNeed:'long',   social:'solo',  rating:9.0, desc:'Descend into a haunting, ruined insect kingdom.' },
  { type:'Game', title:'Cyberpunk 2077',               year:2020, genre:'scifi',   mood:'intense', timeNeed:'long',   social:'solo',  rating:8.1, desc:'Chase immortality through a neon dystopian city.' },
  { type:'Game', title:'Outer Wilds',                  year:2019, genre:'scifi',   mood:'deep',    timeNeed:'medium', social:'solo',  rating:9.2, desc:'Unravel a cosmic mystery in a 22-minute time loop.' },
  { type:'Game', title:'Overcooked! 2',                year:2018, genre:'comedy',  mood:'light',   timeNeed:'short',  social:'group', rating:8.0, desc:'Cook chaotic meals together against the clock.' },
  { type:'Game', title:'Animal Crossing: New Horizons',year:2020, genre:'cozy',    mood:'relaxed', timeNeed:'long',   social:'group', rating:8.5, desc:'Build a peaceful island life at your own pace.' },
  { type:'Game', title:'God of War Ragnarok',          year:2022, genre:'action',  mood:'intense', timeNeed:'long',   social:'solo',  rating:9.4, desc:'Kratos and Atreus face the end of the Nine Realms.' },
  { type:'Game', title:'Balatro',                      year:2024, genre:'cozy',    mood:'relaxed', timeNeed:'short',  social:'solo',  rating:9.0, desc:'A poker-meets-roguelike deckbuilder you can\'t stop.' },
  { type:'Game', title:'Celeste',                      year:2018, genre:'action',  mood:'deep',    timeNeed:'medium', social:'solo',  rating:9.0, desc:'Climb a mountain and your own anxiety, leap by leap.' },
  { type:'Game', title:'Phasmophobia',                 year:2020, genre:'horror',  mood:'intense', timeNeed:'short',  social:'group', rating:8.2, desc:'Hunt ghosts with friends, if your nerves can take it.' },
  { type:'Game', title:'Forza Horizon 5',              year:2021, genre:'action',  mood:'relaxed', timeNeed:'medium', social:'group', rating:9.0, desc:'Cruise a gorgeous open-world Mexico in any car.' },
  { type:'Game', title:'The Witcher 3: Wild Hunt',     year:2015, genre:'action',  mood:'deep',    timeNeed:'long',   social:'solo',  rating:9.3, desc:'Hunt monsters and make hard choices in a war-torn land.' },
  { type:'Game', title:'Untitled Goose Game',          year:2019, genre:'comedy',  mood:'light',   timeNeed:'short',  social:'any',   rating:8.0, desc:'Be a horrible goose and ruin a village\'s morning.' },
  { type:'Game', title:'Journey',                      year:2012, genre:'cozy',    mood:'relaxed', timeNeed:'short',  social:'solo',  rating:9.0, desc:'A wordless, beautiful pilgrimage toward a mountain.' },
  { type:'Game', title:'Cuphead',                      year:2017, genre:'action',  mood:'intense', timeNeed:'medium', social:'group', rating:8.5, desc:'A run-and-gun boss rush in 1930s cartoon style.' },
];

module.exports = { TITLES };
